"""
Django settings for django_react_study project.

Generated by 'django-admin startproject' using Django 3.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

from django.urls import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#파일이 저장되는 경로의 절대경로의 부모의 부모 경로 즉 -> 프로젝트 최상단 폴더로 경로 저장


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$90i#$xrxclk%$qys3m-&pvm5i)$=*826$f!$an4i^97q37-fg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '6093-211-36-157-35.ngrok.io',
    '127.0.0.1',
]
CSRF_TRUSTED_ORIGINS=[
    '6093-211-36-157-35.ngrok.io'
]


# Application definition

INSTALLED_APPS = [
    #django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #third apps
    'bootstrap4',
    'django_extensions',
    'debug_toolbar',
    #local apps
    'blog_example',
    'jstagram',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'django_react_study.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ #app관련 설정 넣는 공간(File System Template Loader) 
            os.path.join(BASE_DIR, 'django_react_study', 'templates') #경로 지정 
            
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_react_study.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT=os.path.join(BASE_DIR, 'staticfiles' )
STATICFILES_DIRS=[
    os.path.join(BASE_DIR, 'jstagram', 'static')
]


import mimetypes
mimetypes.add_type("application/javascript", ".js", True) #debug_tool 화면에 안뜨는거 해결

MEDIA_URL='/media/' #파일에 대한 url 접근시에 사용됨
MEDIA_ROOT=os.path.join(BASE_DIR, 'media') #업로드 되는 파일을 저장하는 경로 지정/ 최상단 폴더 밑에 media 라는 폴더에 저장하겠다는거임

INTERNAL_IPS=['127.0.0.1'] #debug toolbar 추가하는 과정(공식문서로 확인 가능)


from django.contrib.messages import constants as messages_content

MESSAGE_TAGS={messages_content.DEBUG:'secondary', messages_content.ERROR: 'danger'}
#html 마크업시 워딩 매칭이 안되서 편하게 쓰기 위해서 매핑해주는 모습

LOGOUT_REDIRECT_URL=reverse_lazy('login')
